"""
Static catalog of completed projects shown in the portfolio.

Kept as a plain Python list (not a Django model) on purpose: the content is
fixed, edits are trivial, and there is no admin / multi-author workflow that
would justify a database table. Promote to a model only when an editor needs
to manage projects without touching code.
"""

PROJECTS = [
    {
        "slug": "dentalsmile",
        "title": "DentalSmile",
        "category": "Landing Page",
        "industry": "Healthcare · Dental",
        "image": "mainapp/img/projects/dental.jpg",
        "html_file": "mainapp/projects/dentalsmile.html",
        "short_desc": "Dental clinic landing page with appointment booking, patient testimonials, and WhatsApp integration.",
        "long_desc": "A high-converting landing page for a private dental practice. We focused on trust signals — real patient reviews, certifications, before/after gallery — and a one-tap WhatsApp booking flow that eliminates the friction of traditional contact forms.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "WhatsApp API", "Google Maps"],
        "highlight_metric": "+300%",
        "highlight_label": "appointment bookings in month 1",
        "year": 2024,
    },
    {
        "slug": "ironforge-gym",
        "title": "IronForge Gym",
        "category": "Landing Page",
        "industry": "Fitness",
        "image": "mainapp/img/projects/gym.jpg",
        "html_file": "mainapp/projects/ironforge-gym.html",
        "short_desc": "High-energy gym landing page with membership plans, trainers gallery, and lead capture form.",
        "long_desc": "A bold, conversion-focused landing for a boutique gym. Mobile-first design with sticky CTAs, membership comparison table, and a lead form that pipes directly into the owner's WhatsApp inbox. Designed to look as intense as the workouts.",
        "tech_stack": ["HTML5", "Bootstrap 5", "CSS Animations", "JavaScript", "Lead Forms"],
        "highlight_metric": "2x",
        "highlight_label": "monthly membership sign-ups",
        "year": 2024,
    },
    {
        "slug": "lumiere-botanica",
        "title": "Lumiere Botanica",
        "category": "E-commerce",
        "industry": "Beauty · Skincare",
        "image": "mainapp/img/projects/ecomemrce.jpg",
        "html_file": "mainapp/projects/lumiere-botanica.html",
        "short_desc": "Luxury botanical skincare store with product catalog, cart, and Stripe payment integration.",
        "long_desc": "Full e-commerce experience for a premium skincare brand. Product catalog with categories and filters, shopping cart, secure checkout flow, and Stripe payment integration ready for the US market. Designed to feel luxurious from the first scroll.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Stripe", "Cart Logic"],
        "highlight_metric": "3x",
        "highlight_label": "online sales in 90 days",
        "year": 2024,
    },
    {
        "slug": "brasakfire",
        "title": "BrasakFire",
        "category": "Landing Page",
        "industry": "Restaurant · BBQ",
        "image": "mainapp/img/projects/restaurante.jpg",
        "html_file": "mainapp/projects/brasakfire.html",
        "short_desc": "BBQ restaurant landing page with menu showcase, online reservations, and Google Maps integration.",
        "long_desc": "Mouth-watering landing page for a Brazilian-style BBQ restaurant. Visual-heavy menu, story-driven hero, embedded Google Maps, and an online reservation flow that hands the booking off to staff via WhatsApp in real time.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Google Maps", "WhatsApp API"],
        "highlight_metric": "+180%",
        "highlight_label": "weekend reservations",
        "year": 2024,
    },
    {
        "slug": "structura",
        "title": "Structura Constructora",
        "category": "Corporate",
        "industry": "Construction",
        "image": "mainapp/img/projects/constru.jpg",
        "html_file": "mainapp/projects/structura.html",
        "short_desc": "Construction company corporate site with project gallery, stats showcase, and quote request module.",
        "long_desc": "Professional corporate site for a construction firm pursuing larger commercial contracts. Project portfolio gallery, animated stats counter, certifications, team page, and a quote-request form designed to capture serious B2B leads.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Quote Forms", "SEO"],
        "highlight_metric": "+5",
        "highlight_label": "enterprise contracts won",
        "year": 2024,
    },
    {
        "slug": "seguros-com",
        "title": "Seguros.com",
        "category": "Web App",
        "industry": "Insurance · InsurTech",
        "image": "mainapp/img/projects/soat.jpg",
        "html_file": "mainapp/projects/seguros-com.html",
        "short_desc": "Insurance platform with instant quotes, coverage comparison, and online checkout in minutes.",
        "long_desc": "An insurance comparison and purchase platform that turns a 30-minute phone call into a 3-minute online flow. Multi-step quote form, side-by-side coverage comparison, and integrated checkout. Built for high-volume lead conversion.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Multi-step Forms", "Validation"],
        "highlight_metric": "85%",
        "highlight_label": "quote-to-checkout completion",
        "year": 2024,
    },
    {
        "slug": "ramirez-asociados",
        "title": "Ramirez & Associates",
        "category": "Corporate",
        "industry": "Legal Services",
        "image": "mainapp/img/projects/abogado.jpg",
        "html_file": "mainapp/projects/ramirez-asociados.html",
        "short_desc": "Law firm website with practice areas, attorney profiles, and appointment scheduling system.",
        "long_desc": "An elegant, trust-first website for a corporate law firm. Practice areas, attorney bios with credentials, case studies, and an appointment booking system. Designed to convey authority and convert visitors into qualified consultations.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Booking System", "SEO"],
        "highlight_metric": "+220%",
        "highlight_label": "qualified consultations",
        "year": 2024,
    },
    {
        "slug": "vialidad",
        "title": "Vialidad Driving School",
        "category": "Landing Page",
        "industry": "Education · Training",
        "image": "mainapp/img/projects/conducir.jpg",
        "html_file": "mainapp/projects/vialidad.html",
        "short_desc": "Driving school landing page with course catalog, instructor profiles, and online enrollment.",
        "long_desc": "A friendly, student-focused landing page for a driving school. Course tiers with transparent pricing, instructor cards with experience badges, success stories, and a frictionless online enrollment flow that pre-fills WhatsApp messages.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Enrollment Forms"],
        "highlight_metric": "+150%",
        "highlight_label": "monthly enrollments",
        "year": 2024,
    },
    {
        "slug": "mente-plena",
        "title": "Mente Plena Psychology",
        "category": "Landing Page",
        "industry": "Healthcare · Mental Health",
        "image": "mainapp/img/projects/psicologa.jpg",
        "html_file": "mainapp/projects/mente-plena.html",
        "short_desc": "Psychology practice site with therapist profiles, session booking, and service rate information.",
        "long_desc": "A calm, reassuring website for a psychology practice. Therapist profiles with specialties, session types and rates, FAQs that address common hesitations, and a confidential booking flow. Designed to make a hard first step feel easy.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Booking", "Privacy-first"],
        "highlight_metric": "4x",
        "highlight_label": "weekly session bookings",
        "year": 2024,
    },
    {
        "slug": "bella-spa",
        "title": "Bella Spa",
        "category": "Landing Page",
        "industry": "Wellness · Beauty",
        "image": "mainapp/img/projects/spa.jpg",
        "html_file": "mainapp/projects/bella-spa.html",
        "short_desc": "Luxury wellness and spa center with treatment catalog, online reservations, and photo gallery.",
        "long_desc": "A serene, premium-feeling landing page for a luxury spa. Treatment catalog with descriptions and prices, immersive photo gallery, gift card upsell, and an online reservation flow that fills appointments while the team focuses on guests.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Image Gallery", "Reservations"],
        "highlight_metric": "+240%",
        "highlight_label": "online reservations",
        "year": 2024,
    },
    {
        "slug": "wanderlust-travel",
        "title": "Wanderlust Travel",
        "category": "Corporate",
        "industry": "Travel · Tourism",
        "image": "mainapp/img/projects/viaje.jpg",
        "html_file": "mainapp/projects/wanderlust-travel.html",
        "short_desc": "Travel agency website with destination packages, tour galleries, and trip booking system.",
        "long_desc": "An inspiring travel agency website built around storytelling and stunning destination imagery. Curated tour packages, immersive galleries, traveler testimonials, and a multi-step booking flow tailored for international clients.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Multi-step Booking", "Galleries"],
        "highlight_metric": "+190%",
        "highlight_label": "package bookings",
        "year": 2024,
    },
    {
        "slug": "colombia-viva",
        "title": "Colombia Viva Tours",
        "category": "Landing Page",
        "industry": "Travel · Adventure",
        "image": "mainapp/img/projects/otro.jpg",
        "html_file": "mainapp/projects/colombia-viva.html",
        "short_desc": "Adventure travel landing page with immersive visuals, itinerary previews, and quote request form.",
        "long_desc": "A bold adventure-travel landing page targeting US travelers visiting Colombia. Full-bleed imagery, day-by-day itineraries, real traveler reviews, and a quote-request form that turns curiosity into qualified inquiries within minutes.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Lead Capture"],
        "highlight_metric": "+260%",
        "highlight_label": "international inquiries",
        "year": 2024,
    },
    {
        "slug": "muvit",
        "title": "MuvIt Moving Co.",
        "category": "Landing Page",
        "industry": "Logistics · Moving",
        "image": "mainapp/img/projects/mundaza.jpg",
        "html_file": "mainapp/projects/muvit.html",
        "short_desc": "Moving and logistics company site with service tiers, instant quote calculator, and fleet showcase.",
        "long_desc": "A trust-driven landing page for a moving and logistics company. Three-tier service plans, an instant quote calculator that estimates moves on the fly, fleet gallery, and insured-mover badges that overcome the #1 objection in the industry.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Quote Calculator"],
        "highlight_metric": "+170%",
        "highlight_label": "qualified leads",
        "year": 2024,
    },
    {
        "slug": "patitas-vet",
        "title": "Patitas Vet",
        "category": "Landing Page",
        "industry": "Healthcare · Veterinary",
        "image": "mainapp/img/projects/veterarianria.jpg",
        "html_file": "mainapp/projects/patitas-vet.html",
        "short_desc": "Veterinary clinic site with services, appointment booking, pet grooming section, and emergency info.",
        "long_desc": "A warm, family-friendly veterinary clinic site. Services overview, appointment booking, grooming add-ons, and a clearly visible emergency contact line. Designed to feel as caring as the staff inside the clinic.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Appointment Booking"],
        "highlight_metric": "+200%",
        "highlight_label": "first-time pet owners booked",
        "year": 2024,
    },
    {
        "slug": "devcraft",
        "title": "DevCraft Software",
        "category": "Portfolio",
        "industry": "Software · Tech",
        "image": "mainapp/img/projects/software.jpg",
        "html_file": "mainapp/projects/devcraft.html",
        "short_desc": "Developer portfolio with live code preview, tech stack showcase, and project case studies.",
        "long_desc": "A developer-focused portfolio site with terminal-inspired design, live code previews, animated tech-stack showcase, and detailed case studies. Built to win freelance contracts by showing — not telling — technical depth.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Code Animations"],
        "highlight_metric": "+12",
        "highlight_label": "freelance contracts in Q1",
        "year": 2024,
    },
    {
        "slug": "premium-homes",
        "title": "Premium Homes",
        "category": "Corporate",
        "industry": "Real Estate",
        "image": "mainapp/img/projects/constructura.jpg",
        "html_file": "mainapp/projects/premium-homes.html",
        "short_desc": "Real estate developer site with property listings, virtual tours, and mortgage calculator integration.",
        "long_desc": "A premium real estate developer website. Property listings with detailed specs, virtual tour embeds, an integrated mortgage calculator that pre-qualifies buyers, and a lead form that routes serious inquiries straight to the sales team.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Mortgage Calculator", "Tours"],
        "highlight_metric": "+8",
        "highlight_label": "units pre-sold from the site",
        "year": 2024,
    },
    {
        "slug": "ironforge-v2",
        "title": "IronForge Gym v2",
        "category": "Landing Page",
        "industry": "Fitness",
        "image": "mainapp/img/projects/gym2.jpg",
        "html_file": "mainapp/projects/ironforge-v2.html",
        "short_desc": "Gym landing page redesign with full-width imagery, class schedules, and membership comparison.",
        "long_desc": "A complete redesign of the original IronForge landing — full-bleed imagery, weekly class schedule, side-by-side membership comparison, and member success stories. Built around what actually drove conversions in version one.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Schedules", "A/B-tested CTAs"],
        "highlight_metric": "+45%",
        "highlight_label": "conversion rate vs v1",
        "year": 2025,
    },
]

PROJECTS_BY_SLUG = {p["slug"]: p for p in PROJECTS}
